---
apiVersion: v1
kind: Namespace
metadata:
  name: conformance
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: conformance
  name: conformance-serviceaccount
  namespace: conformance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    component: conformance
  name: conformance-serviceaccount-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conformance-serviceaccount
subjects:
- kind: ServiceAccount
  name: conformance-serviceaccount
  namespace: conformance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    component: conformance
  name: conformance-serviceaccount
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '/metrics'
  - '/logs'
  - '/logs/*'
  verbs:
  - 'get'
---
apiVersion: v1
kind: Pod
metadata:
  name: e2e-conformance-test
  namespace: conformance
spec:
  containers:
  - name: conformance-container
    image: decomads/kube-conformance-azure:v1.13
    imagePullPolicy: Always
    env:
    - name: E2E_FOCUS
      value: "Dynamic Provisioning|DynamicProvisioner"
    - name: CLOUD_CONFIG_FILE
      value: "/root/azure_config/azure.yaml"
    - name: E2E_SKIP
      value: "Alpha|\\[Flaky\\]"
    - name: E2E_PROVIDER
      value: "azure"
    - name: E2E_PARALLEL
      value: "false"
    - name: E2E_VERBOSITY
      value: "4"
    command: ["/run_e2e.sh"]
    volumeMounts:
    - name: output-volume
      mountPath: /tmp/results
    - name: cloud-config
      mountPath: "/root/azure_config/"
  volumes:
  - name: cloud-config
    configMap:
      name: game-config
  - name: output-volume
    hostPath:
      path: /tmp/results
  restartPolicy: Never
  serviceAccountName: conformance-serviceaccount
