apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/eksctl/ca.crt
    server: https://60253E1A2070993E75580C13060EB748.sk1.eu-west-1.eks.amazonaws.com
  name: prod.eu-west-1.eksctl.io
contexts:
- context:
    cluster: prod.eu-west-1.eksctl.io
    user: kubelet@prod.eu-west-1.eksctl.io
  name: kubelet@prod.eu-west-1.eksctl.io
current-context: kubelet@prod.eu-west-1.eksctl.io
kind: Config
preferences: {}
users:
- name: kubelet@prod.eu-west-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - prod
      command: aws-iam-authenticator
      env: null
